### ISSUE TITLE
No Package found

### ISSUE THREAD

**Issue by cyberbharathi** [sourcegraph/sourcegraph-git-extras#223]
I could not find any package in the name of "sourcegraph-git-extras" on npm. Is this a private package? If this is a private package when sourcegraph will publish it?

**Comment by muratsu** [comment]
Hey @cyberbharathi this is not a npm package. It's a Sourcegraph extension. To learn more about extensions, please visit the [docs](https://docs.sourcegraph.com/extensions/)
